version: '3.8'

services:
  db:
    image: postgres:14
    container_name: personal_loan_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personal_loan
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: personal_loan_app
    restart: always
    depends_on:
      - db
    ports:
      - '5001:5000'
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: personal_loan
    volumes:
      - .:/app
    command: ['npm', 'run', 'dev']

volumes:
  db_data:
